name: Github Action for Lando

on:
  push:
    branches:
     - master

jobs:     
  build-and-deploy:
    name: Build and Deploy a Lando-based project
    runs-on: ubuntu-18.04
    container: node:10-jessie
    steps:
    - uses: actions/checkout@v1
    - name: Before Install
      run: |
        apt-get -y update
        apt-get -y install cgroup-bin
        bash -c "curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.5.4/hyperdrive > /usr/local/bin/hyperdrive"
        chmod +x /usr/local/bin/hyperdrive
    - name: Startup Lando
      run: |
        hyperdrive -y --name "Github Actions" --email scott@campaignupgrade.org
        lando version
        lando start
